### ISSUE TITLE
Create new Endpoint that is easier to request all scouter report statuses

### ISSUE THREAD

**Issue by Awesomeplayer165** [barryb5/Scouting-Server#4]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/70717139/209700888-613b287c-ad24-4c11-898b-d9e1ff742ad2.png">

**Comment by Awesomeplayer165** [comment]
the idea is that the tournament key can be paired with the match keys to create:
`2022cc`_`qm2`, which can then be paired for each individual 6 scout reports in that match like, `2022cc_qm2_1`, `2022cc_qm2_2`, `2022cc_qm2_3`

**Comment by barryb5** [comment]
match key comes from tba api already as 2022cc_qm2 that's not me. Adding the _2 at the end is me because I need to split the match into 6 unique keys for scoutReports. idk what you're asking for in the comment but the endpoint exists now
