### ISSUE TITLE
Convert match numbers to match keys

### ISSUE THREAD

**Issue by Awesomeplayer165** [barryb5/Scouting-Server#5]
With this endpoint, for example, 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/70717139/209701271-4991067d-aba6-4c76-8644-3891a90783c8.png">
we have no say in what the match key that is given back to us since there is no query parameter to accept match keys (which distinguishes between quarter matches and finals, for example)

**Comment by barryb5** [comment]
it takes a matchKey now
